import datetime
from app.database import get_connection

SENHA_MI_PADRAO = "Invec2025"


LOG_RETENCAO_BIPAGEM_DIAS = 90
LOG_RETENCAO_GERAL_DIAS   = 365   # EDICAO, EXCLUSAO, ALERTA, CONSOLIDACAO
RELATORIOS_RETENCAO_DIAS  = 180
PASTA_RELATORIOS = r"C:\Invec\relatorios"


def run_migrations():
    _migrar_operadores_app()
    _migrar_coluna(
        "INVENTARIO_TEMP", "OPERADOR",
        "ALTER TABLE INVENTARIO_TEMP ADD OPERADOR VARCHAR(100)",
    )
    _migrar_coluna(
        "INVENTARIO_TEMP", "QTDEATUAL_SNAP",
        "ALTER TABLE INVENTARIO_TEMP ADD QTDEATUAL_SNAP DECIMAL(15,4)",
    )
    _migrar_coluna(
        "INVENTARIO_TEMP", "SESSION_ID",
        "ALTER TABLE INVENTARIO_TEMP ADD SESSION_ID VARCHAR(36)",
    )
    # Identifica registros do Invec vs. Automec — impede DELETE acidental de dados do Automec
    _migrar_coluna(
        "INVENTARIO_TEMP", "ORIGEM",
        "ALTER TABLE INVENTARIO_TEMP ADD ORIGEM VARCHAR(20)",
    )
    _migrar_coluna(
        "INVENTARIO", "OPERADOR",
        "ALTER TABLE INVENTARIO ADD OPERADOR VARCHAR(100)",
    )
    _migrar_log_inventario()
    # SESSION_ID no log permite rastrear edições por sessão (detecção de fraude FRAUDE-2)
    _migrar_coluna(
        "LOG_INVENTARIO", "SESSION_ID",
        "ALTER TABLE LOG_INVENTARIO ADD SESSION_ID VARCHAR(36)",
    )
    _migrar_inventario_sessao()
    # Colunas que podem estar faltando em servidores atualizados de versões anteriores
    _migrar_coluna("INVENTARIO_SESSAO", "OPERADOR", "ALTER TABLE INVENTARIO_SESSAO ADD OPERADOR VARCHAR(100)")
    _migrar_coluna("INVENTARIO_SESSAO", "USUARIO",  "ALTER TABLE INVENTARIO_SESSAO ADD USUARIO VARCHAR(50)")
    _migrar_coluna("INVENTARIO_SESSAO", "STATUS",   "ALTER TABLE INVENTARIO_SESSAO ADD STATUS VARCHAR(20) DEFAULT 'ABERTA'")
    _migrar_coluna("INVENTARIO_SESSAO", "INICIO",   "ALTER TABLE INVENTARIO_SESSAO ADD INICIO TIMESTAMP DEFAULT CURRENT_TIMESTAMP")
    _migrar_coluna("INVENTARIO_SESSAO", "FIM",      "ALTER TABLE INVENTARIO_SESSAO ADD FIM TIMESTAMP")
    _migrar_coluna(
        "USUARIOS", "SENHAMOBILE",
        "ALTER TABLE USUARIOS ADD SENHAMOBILE VARCHAR(100)",
    )
    _migrar_coluna(
        "USUARIOS", "MOBILE_ADMIN",
        "ALTER TABLE USUARIOS ADD MOBILE_ADMIN SMALLINT DEFAULT 0",
    )
    # Tabelas criadas ANTES dos índices — _migrar_indices_log depende delas existirem
    _migrar_lotes_processados()
    _migrar_scans_processados()
    _migrar_usuario_deposito()
    _migrar_indices_log()
    _migrar_indice_log_tipo()
    _limpar_log_bipagem()
    _reset_sessoes_consolidando()
    _migrar_log_data_hora_timestamp()
    _limpar_log_geral()
    _limpar_relatorios_antigos()
    _limpar_idempotencia_antiga()
    _migrar_senha_mi_padrao()


def _migrar_operadores_app():
    try:
        with get_connection() as con:
            cur = con.cursor()
            cur.execute(
                "SELECT COUNT(*) FROM RDB$RELATIONS WHERE RDB$RELATION_NAME = 'OPERADORES_APP'"
            )
            if cur.fetchone()[0] == 0:
                cur.execute(
                    """
                    CREATE TABLE OPERADORES_APP (
                        ID      INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        NOME    VARCHAR(100) NOT NULL,
                        ATIVO   SMALLINT DEFAULT 1 NOT NULL
                    )
                    """
                )
    except Exception as e:
        print(f"[migration] OPERADORES_APP: {e}")


def _migrar_log_inventario():
    try:
        with get_connection() as con:
            cur = con.cursor()
            cur.execute(
                "SELECT COUNT(*) FROM RDB$RELATIONS WHERE RDB$RELATION_NAME = 'LOG_INVENTARIO'"
            )
            if cur.fetchone()[0] == 0:
                cur.execute(
                    """
                    CREATE TABLE LOG_INVENTARIO (
                        ID             INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        TIPO           VARCHAR(20) NOT NULL,
                        CDDEPOSITO     INTEGER,
                        CDPRODUTO      INTEGER,
                        PRODUTO        VARCHAR(200),
                        OPERADOR       VARCHAR(100),
                        LOGIN_USUARIO  VARCHAR(50),
                        QTDE_ANTES     DECIMAL(15,4),
                        QTDE_DEPOIS    DECIMAL(15,4),
                        MOTIVO         VARCHAR(500),
                        DEVICE_ID      VARCHAR(100),
                        DATA_HORA      TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
                    )
                    """
                )
    except Exception as e:
        print(f"[migration] LOG_INVENTARIO: {e}")


def _limpar_log_bipagem():
    # Limita a 10 000 registros por execução para evitar travar o banco em servidores com muitos logs
    try:
        with get_connection() as con:
            cur = con.cursor()
            cur.execute(
                "DELETE FROM LOG_INVENTARIO "
                "WHERE ID IN ("
                "  SELECT FIRST 10000 ID FROM LOG_INVENTARIO "
                "  WHERE TIPO = 'BIPAGEM' "
                "  AND DATA_HORA < DATEADD(DAY, ?, CURRENT_TIMESTAMP) "
                "  ORDER BY DATA_HORA ASC"
                ")",
                (-LOG_RETENCAO_BIPAGEM_DIAS,),
            )
            apagados = cur.rowcount
            if apagados > 0:
                print(f"[migration] LOG_INVENTARIO: {apagados} registros de BIPAGEM antigos removidos")
    except Exception as e:
        print(f"[migration] _limpar_log_bipagem: {e}")


def _migrar_inventario_sessao():
    try:
        with get_connection() as con:
            cur = con.cursor()
            cur.execute(
                "SELECT COUNT(*) FROM RDB$RELATIONS WHERE RDB$RELATION_NAME = 'INVENTARIO_SESSAO'"
            )
            if cur.fetchone()[0] == 0:
                cur.execute(
                    """
                    CREATE TABLE INVENTARIO_SESSAO (
                        SESSION_ID  VARCHAR(36)  NOT NULL,
                        CDDEPOSITO  INTEGER      NOT NULL,
                        OPERADOR    VARCHAR(100),
                        USUARIO     VARCHAR(50),
                        STATUS      VARCHAR(20)  DEFAULT 'ABERTA' NOT NULL,
                        INICIO      TIMESTAMP    DEFAULT CURRENT_TIMESTAMP NOT NULL,
                        FIM         TIMESTAMP,
                        CONSTRAINT PK_INV_SESSAO PRIMARY KEY (SESSION_ID)
                    )
                    """
                )
    except Exception as e:
        print(f"[migration] INVENTARIO_SESSAO: {e}")


def _migrar_indices_log():
    indices = [
        ("IDX_LOG_INV_DEPOSITO",    "CREATE INDEX IDX_LOG_INV_DEPOSITO ON LOG_INVENTARIO (CDDEPOSITO)"),
        ("IDX_LOG_INV_DATA",        "CREATE DESCENDING INDEX IDX_LOG_INV_DATA ON LOG_INVENTARIO (DATA_HORA)"),
        ("IDX_INVTEMP_PROD_DEP",    "CREATE INDEX IDX_INVTEMP_PROD_DEP ON INVENTARIO_TEMP (CDPRODUTO, CDDEPOSITO)"),
        ("IDX_INVTEMP_SESSION",     "CREATE INDEX IDX_INVTEMP_SESSION ON INVENTARIO_TEMP (SESSION_ID, CDDEPOSITO)"),
        # Índice composto cobre NOT EXISTS com SESSION_ID (PERF-4)
        ("IDX_INVTEMP_PROD_DEP_SES","CREATE INDEX IDX_INVTEMP_PROD_DEP_SES ON INVENTARIO_TEMP (CDPRODUTO, CDDEPOSITO, SESSION_ID)"),
        # Índice em LOTES_SYNC_PROCESSADOS para auditoria e limpeza por sessão (INST-4)
        ("IDX_LOTES_SESSION",       "CREATE INDEX IDX_LOTES_SESSION ON LOTES_SYNC_PROCESSADOS (SESSION_ID)"),
        # Índice para rastrear edições por sessão (FRAUDE-2)
        ("IDX_LOG_SESSION",         "CREATE INDEX IDX_LOG_SESSION ON LOG_INVENTARIO (SESSION_ID, TIPO)"),
        # Índice de permissões por usuário/depósito (FRAUDE-3)
        ("IDX_USUDEP_USUARIO",      "CREATE INDEX IDX_USUDEP_USUARIO ON USUARIO_DEPOSITO (IDUSUARIO)"),
    ]
    for nome, ddl in indices:
        try:
            with get_connection() as con:
                cur = con.cursor()
                cur.execute(
                    "SELECT COUNT(*) FROM RDB$INDICES WHERE RDB$INDEX_NAME = ?",
                    (nome,),
                )
                if cur.fetchone()[0] == 0:
                    cur.execute(ddl)
        except Exception as e:
            print(f"[migration] índice {nome}: {e}")


def _migrar_indice_log_tipo():
    try:
        with get_connection() as con:
            cur = con.cursor()
            cur.execute(
                "SELECT COUNT(*) FROM RDB$INDICES WHERE RDB$INDEX_NAME = 'IDX_LOG_INV_TIPO'",
            )
            if cur.fetchone()[0] == 0:
                cur.execute("CREATE INDEX IDX_LOG_INV_TIPO ON LOG_INVENTARIO (TIPO)")
    except Exception as e:
        print(f"[migration] IDX_LOG_INV_TIPO: {e}")


def _limpar_log_geral():
    """Remove logs operacionais antigos. EXCLUSAO e CONSOLIDACAO nunca são apagados (auditoria permanente)."""
    # FRAUDE-7: EXCLUSAO e CONSOLIDACAO retidos indefinidamente para rastreabilidade fiscal
    # Limite de 10 000 por execução para não travar o banco na subida do serviço
    try:
        with get_connection() as con:
            cur = con.cursor()
            cur.execute(
                "DELETE FROM LOG_INVENTARIO "
                "WHERE ID IN ("
                "  SELECT FIRST 10000 ID FROM LOG_INVENTARIO "
                "  WHERE TIPO NOT IN ('EDICAO_SUSPEITA', 'ALERTA_REESCAN', 'EXCLUSAO', 'CONSOLIDACAO') "
                "  AND DATA_HORA < DATEADD(DAY, ?, CURRENT_TIMESTAMP) "
                "  ORDER BY DATA_HORA ASC"
                ")",
                (-LOG_RETENCAO_GERAL_DIAS,),
            )
            apagados = cur.rowcount
            if apagados > 0:
                print(f"[migration] LOG_INVENTARIO: {apagados} registros antigos removidos")
    except Exception as e:
        print(f"[migration] _limpar_log_geral: {e}")


def _limpar_relatorios_antigos():
    import os, time
    try:
        if not os.path.isdir(PASTA_RELATORIOS):
            return
        limite = time.time() - RELATORIOS_RETENCAO_DIAS * 86400
        apagados = 0
        for nome in os.listdir(PASTA_RELATORIOS):
            if not nome.startswith("consolidacao_") or not nome.endswith(".txt"):
                continue
            caminho = os.path.join(PASTA_RELATORIOS, nome)
            if os.path.getmtime(caminho) < limite:
                os.remove(caminho)
                apagados += 1
        if apagados > 0:
            print(f"[migration] Relatorios: {apagados} arquivos antigos removidos")
    except Exception as e:
        print(f"[migration] _limpar_relatorios_antigos: {e}")


def _migrar_lotes_processados():
    try:
        with get_connection() as con:
            cur = con.cursor()
            cur.execute(
                "SELECT COUNT(*) FROM RDB$RELATIONS WHERE RDB$RELATION_NAME = 'LOTES_SYNC_PROCESSADOS'"
            )
            if cur.fetchone()[0] == 0:
                cur.execute(
                    """
                    CREATE TABLE LOTES_SYNC_PROCESSADOS (
                        LOTE_ID    VARCHAR(36)  NOT NULL PRIMARY KEY,
                        SESSION_ID VARCHAR(36),
                        DATA_HORA  TIMESTAMP    DEFAULT CURRENT_TIMESTAMP NOT NULL
                    )
                    """
                )
    except Exception as e:
        print(f"[migration] LOTES_SYNC_PROCESSADOS: {e}")


def _migrar_scans_processados():
    """Tabela de idempotência por scan individual — evita duplicata quando scan online sofre timeout."""
    try:
        with get_connection() as con:
            cur = con.cursor()
            cur.execute(
                "SELECT COUNT(*) FROM RDB$RELATIONS WHERE RDB$RELATION_NAME = 'SCANS_PROCESSADOS'"
            )
            if cur.fetchone()[0] == 0:
                cur.execute(
                    """
                    CREATE TABLE SCANS_PROCESSADOS (
                        SCAN_ID    VARCHAR(36)  NOT NULL PRIMARY KEY,
                        SESSION_ID VARCHAR(36),
                        CDPRODUTO  INTEGER,
                        DATA_HORA  TIMESTAMP    DEFAULT CURRENT_TIMESTAMP NOT NULL
                    )
                    """
                )
                cur.execute(
                    "CREATE INDEX IDX_SCANS_SESSION ON SCANS_PROCESSADOS (SESSION_ID)"
                )
    except Exception as e:
        print(f"[migration] SCANS_PROCESSADOS: {e}")


def _reset_sessoes_consolidando():
    """Reseta sessões presas em STATUS='CONSOLIDANDO' após restart do servidor.
    Seguro: se o servidor acabou de iniciar, qualquer 'CONSOLIDANDO' é de uma consolidação que morreu no meio.
    """
    try:
        with get_connection() as con:
            cur = con.cursor()
            cur.execute(
                "UPDATE INVENTARIO_SESSAO SET STATUS = 'ABERTA' WHERE STATUS = 'CONSOLIDANDO'"
            )
    except Exception as e:
        print(f"[migration] reset CONSOLIDANDO: {e}")


def _migrar_usuario_deposito():
    """Tabela de permissão explícita por usuário/depósito (FRAUDE-3)."""
    try:
        with get_connection() as con:
            cur = con.cursor()
            cur.execute(
                "SELECT COUNT(*) FROM RDB$RELATIONS WHERE RDB$RELATION_NAME = 'USUARIO_DEPOSITO'"
            )
            if cur.fetchone()[0] == 0:
                cur.execute(
                    """
                    CREATE TABLE USUARIO_DEPOSITO (
                        IDUSUARIO  INTEGER NOT NULL,
                        CDDEPOSITO INTEGER NOT NULL,
                        CONSTRAINT PK_USUARIO_DEPOSITO PRIMARY KEY (IDUSUARIO, CDDEPOSITO)
                    )
                    """
                )
    except Exception as e:
        print(f"[migration] USUARIO_DEPOSITO: {e}")


def _migrar_log_data_hora_timestamp():
    """Converte LOG_INVENTARIO.DATA_HORA de DATE para TIMESTAMP se necessário (instâncias antigas)."""
    try:
        with get_connection() as con:
            cur = con.cursor()
            cur.execute(
                """
                SELECT F.RDB$FIELD_TYPE
                FROM RDB$RELATION_FIELDS RF
                JOIN RDB$FIELDS F ON F.RDB$FIELD_NAME = RF.RDB$FIELD_SOURCE
                WHERE RF.RDB$RELATION_NAME = 'LOG_INVENTARIO'
                  AND RF.RDB$FIELD_NAME = 'DATA_HORA'
                """
            )
            row = cur.fetchone()
            if row and row[0] == 12:  # 12 = DATE, 35 = TIMESTAMP
                cur.execute("ALTER TABLE LOG_INVENTARIO ALTER DATA_HORA TYPE TIMESTAMP")
    except Exception as e:
        print(f"[migration] LOG_INVENTARIO DATA_HORA→TIMESTAMP: {e}")


def _limpar_idempotencia_antiga():
    """Remove scan_ids e lote_ids de sessões antigas (>90 dias) — dados de dedup já sem função."""
    try:
        with get_connection() as con:
            cur = con.cursor()
            cur.execute(
                "DELETE FROM SCANS_PROCESSADOS "
                "WHERE DATA_HORA < DATEADD(DAY, -90, CURRENT_TIMESTAMP)"
            )
            apagados_scans = cur.rowcount
            cur.execute(
                "DELETE FROM LOTES_SYNC_PROCESSADOS "
                "WHERE DATA_HORA < DATEADD(DAY, -90, CURRENT_TIMESTAMP)"
            )
            apagados_lotes = cur.rowcount
            if apagados_scans + apagados_lotes > 0:
                print(
                    f"[migration] Idempotência: {apagados_scans} scan_ids e "
                    f"{apagados_lotes} lote_ids antigos removidos"
                )
    except Exception as e:
        print(f"[migration] _limpar_idempotencia_antiga: {e}")


def _migrar_coluna(tabela: str, coluna: str, ddl: str):
    try:
        with get_connection() as con:
            cur = con.cursor()
            cur.execute(
                "SELECT COUNT(*) FROM RDB$RELATION_FIELDS "
                "WHERE RDB$RELATION_NAME = ? AND RDB$FIELD_NAME = ?",
                (tabela.upper(), coluna.upper()),
            )
            if cur.fetchone()[0] == 0:
                cur.execute(ddl)
    except Exception as e:
        print(f"[migration] {tabela}.{coluna}: {e}")


def _migrar_senha_mi_padrao():
    try:
        with get_connection() as con:
            cur = con.cursor()
            cur.execute(
                "UPDATE USUARIOS SET SENHAMOBILE = ? "
                "WHERE UPPER(LOGIN) = 'MI' AND (SENHAMOBILE IS NULL OR SENHAMOBILE = '')",
                (SENHA_MI_PADRAO,),
            )
            if cur.rowcount > 0:
                print(f"[migration] SENHAMOBILE do MI definida como '{SENHA_MI_PADRAO}'. Altere via app em Usuarios.")
    except Exception as e:
        print(f"[migration] senha MI padrao: {e}")
