from app.database import get_connection


LOG_RETENCAO_BIPAGEM_DIAS = 90
LOG_RETENCAO_GERAL_DIAS   = 365   # EDICAO, EXCLUSAO, ALERTA, CONSOLIDACAO
RELATORIOS_RETENCAO_DIAS  = 180
PASTA_RELATORIOS = r"C:\Invec\relatorios"


def run_migrations():
    _migrar_operadores_app()
    _migrar_coluna(
        "INVENTARIO_TEMP", "OPERADOR",
        "ALTER TABLE INVENTARIO_TEMP ADD OPERADOR VARCHAR(100)",
    )
    _migrar_coluna(
        "INVENTARIO_TEMP", "QTDEATUAL_SNAP",
        "ALTER TABLE INVENTARIO_TEMP ADD QTDEATUAL_SNAP DECIMAL(15,4)",
    )
    _migrar_coluna(
        "INVENTARIO", "OPERADOR",
        "ALTER TABLE INVENTARIO ADD OPERADOR VARCHAR(100)",
    )
    _migrar_log_inventario()
    _migrar_indices_log()
    _limpar_log_bipagem()
    _migrar_coluna(
        "USUARIOS", "MOBILE_ADMIN",
        "ALTER TABLE USUARIOS ADD MOBILE_ADMIN SMALLINT DEFAULT 0",
    )
    _migrar_indice_log_tipo()
    _limpar_log_geral()
    _limpar_relatorios_antigos()


def _migrar_operadores_app():
    try:
        with get_connection() as con:
            cur = con.cursor()
            cur.execute(
                "SELECT COUNT(*) FROM RDB$RELATIONS WHERE RDB$RELATION_NAME = 'OPERADORES_APP'"
            )
            if cur.fetchone()[0] == 0:
                cur.execute(
                    """
                    CREATE TABLE OPERADORES_APP (
                        ID      INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        NOME    VARCHAR(100) NOT NULL,
                        ATIVO   SMALLINT DEFAULT 1 NOT NULL
                    )
                    """
                )
    except Exception as e:
        print(f"[migration] OPERADORES_APP: {e}")


def _migrar_log_inventario():
    try:
        with get_connection() as con:
            cur = con.cursor()
            cur.execute(
                "SELECT COUNT(*) FROM RDB$RELATIONS WHERE RDB$RELATION_NAME = 'LOG_INVENTARIO'"
            )
            if cur.fetchone()[0] == 0:
                cur.execute(
                    """
                    CREATE TABLE LOG_INVENTARIO (
                        ID             INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        TIPO           VARCHAR(20) NOT NULL,
                        CDDEPOSITO     INTEGER,
                        CDPRODUTO      INTEGER,
                        PRODUTO        VARCHAR(200),
                        OPERADOR       VARCHAR(100),
                        LOGIN_USUARIO  VARCHAR(50),
                        QTDE_ANTES     DECIMAL(15,4),
                        QTDE_DEPOIS    DECIMAL(15,4),
                        MOTIVO         VARCHAR(500),
                        DEVICE_ID      VARCHAR(100),
                        DATA_HORA      TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
                    )
                    """
                )
    except Exception as e:
        print(f"[migration] LOG_INVENTARIO: {e}")


def _limpar_log_bipagem():
    try:
        with get_connection() as con:
            cur = con.cursor()
            cur.execute(
                "DELETE FROM LOG_INVENTARIO "
                "WHERE TIPO = 'BIPAGEM' "
                "AND DATA_HORA < DATEADD(DAY, ?, CURRENT_TIMESTAMP)",
                (-LOG_RETENCAO_BIPAGEM_DIAS,),
            )
            apagados = cur.rowcount
            if apagados > 0:
                print(f"[migration] LOG_INVENTARIO: {apagados} registros de BIPAGEM antigos removidos")
    except Exception as e:
        print(f"[migration] _limpar_log_bipagem: {e}")


def _migrar_indices_log():
    indices = [
        ("IDX_LOG_INV_DEPOSITO", "CREATE INDEX IDX_LOG_INV_DEPOSITO ON LOG_INVENTARIO (CDDEPOSITO)"),
        ("IDX_LOG_INV_DATA",     "CREATE DESCENDING INDEX IDX_LOG_INV_DATA ON LOG_INVENTARIO (DATA_HORA)"),
        # Índice composto para as subqueries do relatório (MOVIMENTO por produto+depósito)
        ("IDX_INVTEMP_PROD_DEP", "CREATE INDEX IDX_INVTEMP_PROD_DEP ON INVENTARIO_TEMP (CDPRODUTO, CDDEPOSITO)"),
    ]
    for nome, ddl in indices:
        try:
            with get_connection() as con:
                cur = con.cursor()
                cur.execute(
                    "SELECT COUNT(*) FROM RDB$INDICES WHERE RDB$INDEX_NAME = ?",
                    (nome,),
                )
                if cur.fetchone()[0] == 0:
                    cur.execute(ddl)
        except Exception as e:
            print(f"[migration] índice {nome}: {e}")


def _migrar_indice_log_tipo():
    try:
        with get_connection() as con:
            cur = con.cursor()
            cur.execute(
                "SELECT COUNT(*) FROM RDB$INDICES WHERE RDB$INDEX_NAME = 'IDX_LOG_INV_TIPO'",
            )
            if cur.fetchone()[0] == 0:
                cur.execute("CREATE INDEX IDX_LOG_INV_TIPO ON LOG_INVENTARIO (TIPO)")
    except Exception as e:
        print(f"[migration] IDX_LOG_INV_TIPO: {e}")


def _limpar_log_geral():
    """Remove logs antigos de todos os tipos exceto EDICAO_SUSPEITA e ALERTA_REESCAN (guardar mais tempo)."""
    try:
        with get_connection() as con:
            cur = con.cursor()
            cur.execute(
                "DELETE FROM LOG_INVENTARIO "
                "WHERE TIPO NOT IN ('EDICAO_SUSPEITA', 'ALERTA_REESCAN') "
                "AND DATA_HORA < DATEADD(DAY, ?, CURRENT_TIMESTAMP)",
                (-LOG_RETENCAO_GERAL_DIAS,),
            )
            apagados = cur.rowcount
            if apagados > 0:
                print(f"[migration] LOG_INVENTARIO: {apagados} registros antigos removidos")
    except Exception as e:
        print(f"[migration] _limpar_log_geral: {e}")


def _limpar_relatorios_antigos():
    import os, time
    try:
        if not os.path.isdir(PASTA_RELATORIOS):
            return
        limite = time.time() - RELATORIOS_RETENCAO_DIAS * 86400
        apagados = 0
        for nome in os.listdir(PASTA_RELATORIOS):
            if not nome.startswith("consolidacao_") or not nome.endswith(".txt"):
                continue
            caminho = os.path.join(PASTA_RELATORIOS, nome)
            if os.path.getmtime(caminho) < limite:
                os.remove(caminho)
                apagados += 1
        if apagados > 0:
            print(f"[migration] Relatorios: {apagados} arquivos antigos removidos")
    except Exception as e:
        print(f"[migration] _limpar_relatorios_antigos: {e}")


def _migrar_coluna(tabela: str, coluna: str, ddl: str):
    try:
        with get_connection() as con:
            cur = con.cursor()
            cur.execute(
                "SELECT COUNT(*) FROM RDB$RELATION_FIELDS "
                "WHERE RDB$RELATION_NAME = ? AND RDB$FIELD_NAME = ?",
                (tabela.upper(), coluna.upper()),
            )
            if cur.fetchone()[0] == 0:
                cur.execute(ddl)
    except Exception as e:
        print(f"[migration] {tabela}.{coluna}: {e}")
